title: Teo Parashkevov
author:
  name: theoparashkevov
  email: theo.parashkevov@gmail.com

baseurl: ""
url: "https://theoparashkevov.github.io"
# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  My personal development blog.

# --------------------
# Build settings
# --------------------

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc



# --------------------
# Markdown
# --------------------
markdown: kramdown

mathjax: true

kramdown:
  parse_block_html: true

# https://github.com/toshimaru/jekyll-toc
toc:
  min_level: 1
  max_level: 3
  list_id: toc 
  list_class: toc-container
  list_class: toc-list-class
  sublist_class: toc-sublist-class 
  item_class: toc-entry 
  item_prefix: toc- 

# --------------------
# Front Matter
# --------------------
defaults:
  - scope:
      path: ""
    values:
      toc: true


# --------------------
# Theme-specific settings
# --------------------
minima:
  skin: dark
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
    - { platform: github,         user_url: "https://github.com/theoparashkevov" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/teo-parashkevov/" }
    - { platform: youtube,        user_url: "https://www.youtube.com/channel/UCe0mtJP7Pl7JmLG8kDQma-g" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - blog.md
  - projects.md
  - contact.md

google_analytics: G-FL4MFK5HC5

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
